server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/binance/ {
        proxy_pass https://data-api.binance.vision/api/v3/;
        proxy_ssl_server_name on;
        proxy_set_header Host data-api.binance.vision;
    }

    location /api/yahoo/ {
        proxy_pass https://query1.finance.yahoo.com/;
        proxy_ssl_server_name on;
        proxy_set_header Host query1.finance.yahoo.com;
    }
}
